cmd_/home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/objtool/builtin-check.o := gcc -Wp,-MD,/home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/objtool/.builtin-check.o.d -Wp,-MT,/home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/objtool/builtin-check.o -Werror -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -Wstrict-aliasing=3 -Wshadow -Wno-switch-default -Wno-switch-enum -Wno-packed -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu89 -g -I/home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include -I/home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/arch/x86/include/uapi -I/home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/arch/x86/include -I/home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/objtool/arch/x86/include -I/home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/lib -D"BUILD_STR(s)=$(pound)s" -c -o /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/objtool/builtin-check.o builtin-check.c

source_/home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/objtool/builtin-check.o := builtin-check.c

deps_/home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/objtool/builtin-check.o := \
  /usr/include/stdc-predef.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/lib/subcmd/parse-options.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/linux/kernel.h \
  /usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h \
  /usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h \
  /usr/include/assert.h \
  /usr/include/features.h \
  /usr/include/x86_64-linux-gnu/sys/cdefs.h \
  /usr/include/x86_64-linux-gnu/bits/wordsize.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs-64.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/linux/build_bug.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/linux/compiler.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/linux/compiler-gcc.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-linux-gnu/5/include/stdbool.h \
  /usr/lib/gcc/x86_64-linux-gnu/5/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/x86_64-linux-gnu/bits/wchar.h \
  /usr/include/x86_64-linux-gnu/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/arch/x86/include/uapi/asm/bitsperlong.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/asm-generic/bitsperlong.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/x86_64-linux-gnu/asm/posix_types.h \
  /usr/include/x86_64-linux-gnu/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /usr/include/endian.h \
  /usr/include/x86_64-linux-gnu/bits/endian.h \
  /usr/include/x86_64-linux-gnu/bits/byteswap.h \
  /usr/include/x86_64-linux-gnu/bits/types.h \
  /usr/include/x86_64-linux-gnu/bits/typesizes.h \
  /usr/include/x86_64-linux-gnu/bits/byteswap-16.h \
  /usr/include/byteswap.h \
  /usr/include/string.h \
  /usr/include/xlocale.h \
  /usr/include/x86_64-linux-gnu/bits/string.h \
  /usr/include/x86_64-linux-gnu/bits/string2.h \
  /usr/include/stdlib.h \
  /usr/include/x86_64-linux-gnu/bits/string3.h \
  builtin.h \
  objtool.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/linux/list.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/linux/poison.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/linux/hashtable.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/linux/bitops.h \
  /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/limits.h \
  /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/syslimits.h \
  /usr/include/limits.h \
  /usr/include/x86_64-linux-gnu/bits/posix1_lim.h \
  /usr/include/x86_64-linux-gnu/bits/local_lim.h \
  /usr/include/linux/limits.h \
  /usr/include/x86_64-linux-gnu/bits/posix2_lim.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/linux/bits.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/linux/const.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/vdso/const.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/uapi/linux/const.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/vdso/bits.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/asm-generic/bitops.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/asm-generic/bitops/__ffs.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/asm-generic/bitops/__ffz.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/asm-generic/bitops/fls.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/asm-generic/bitops/__fls.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/asm-generic/bitops/fls64.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/asm-generic/bitops/find.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/asm-generic/bitops/hweight.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/asm-generic/bitops/arch_hweight.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/asm-generic/bitops/const_hweight.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/asm-generic/bitops/atomic.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/asm-generic/bitops/non-atomic.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/linux/hash.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/linux/log2.h \
  elf.h \
  /usr/include/stdio.h \
  /usr/include/libio.h \
  /usr/include/_G_config.h \
  /usr/include/wchar.h \
  /usr/include/x86_64-linux-gnu/bits/stdio_lim.h \
  /usr/include/x86_64-linux-gnu/bits/sys_errlist.h \
  /usr/include/x86_64-linux-gnu/bits/stdio.h \
  /usr/include/x86_64-linux-gnu/bits/stdio2.h \
  /usr/include/gelf.h \
  /usr/include/libelf.h \
  /usr/include/x86_64-linux-gnu/sys/types.h \
  /usr/include/time.h \
  /usr/include/x86_64-linux-gnu/sys/select.h \
  /usr/include/x86_64-linux-gnu/bits/select.h \
  /usr/include/x86_64-linux-gnu/bits/sigset.h \
  /usr/include/x86_64-linux-gnu/bits/time.h \
  /usr/include/x86_64-linux-gnu/bits/select2.h \
  /usr/include/x86_64-linux-gnu/sys/sysmacros.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h \
  /usr/include/elf.h \
  /usr/include/x86_64-linux-gnu/bits/auxv.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/linux/rbtree.h \
  /usr/include/linux/stddef.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/linux/jhash.h \
  /home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/include/linux/unaligned/packed_struct.h \

/home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/objtool/builtin-check.o: $(deps_/home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/objtool/builtin-check.o)

$(deps_/home/etudiant/Documents/M2/GNU-LINUX/linux-5.8.12/tools/objtool/builtin-check.o):
